<?php
// This file is normally generated by @wordpress/scripts build tooling.
// For internal DP use (no build step), it's fine to keep it static.
return array(
	'dependencies' => array(
		'wp-blocks',
		'wp-element',
		'wp-components',
		'wp-block-editor',
		'wp-i18n',
	),
	'version' => '1.0.0',
);